### ISSUE TITLE
Persei Required

### ISSUE THREAD

**Issue by medoix** [MaddieM4/djdns-hype-flat#8]
Needed to run "pip install persei"

Otherise got the following

Traceback (most recent call last):
  File "run.py", line 27, in <module>
    from djdns.server import DJServer
  File "/data/programs/dhf/local/lib/python2.7/site-packages/djdns/server.py", line 3, in <module>
    from pymads.server import DnsServer
  File "/data/programs/dhf/local/lib/python2.7/site-packages/pymads-0.5-py2.7.egg/pymads/server.py", line 25, in <module>
    from pymads.consumer import Consumer
  File "/data/programs/dhf/local/lib/python2.7/site-packages/pymads-0.5-py2.7.egg/pymads/consumer.py", line 20, in <module>
    from pymads import request
  File "/data/programs/dhf/local/lib/python2.7/site-packages/pymads-0.5-py2.7.egg/pymads/request.py", line 20, in <module>
    from pymads.packet import Packet
  File "/data/programs/dhf/local/lib/python2.7/site-packages/pymads-0.5-py2.7.egg/pymads/packet.py", line 21, in <module>
    from persei import String, RawData
ImportError: No module named persei

**Comment by MaddieM4** [comment]
Absolutely correct. I will add this to the README.
